version: '3'

services:
  app:
    container_name: php7
    image: php:7.1-apache
    volumes:
      - ".:/var/www/html"
    ports:
      - 80:80
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.6
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sach
    ports:
      - 3306:3306
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment: 
      - "PMA_HOST:mysql"
      - "PMA_USER:root"
      - "PMA_PASSWORD:123456"


    